### ISSUE TITLE
Read and show the book license

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/issues#2]
Books can have license, which is determined by the author.  Readers must use the books in accordance to the license.

## Tasks

- [ ] Make it clear to the user that by reading this book, the user accepts the license
- [ ] Provide a link to the license from where the user can read the license
- [ ] (Optional) detect the license type, such as _Creative Commons Attribution 4.0 International License_ or _Apache License Version 2.0_ and display this
- [ ] Read the text file `LICENSE` from the same folder from where book is opened.  Use the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/) if one is not provided
