### ISSUE TITLE
Show sections and subsections in the table of contents

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/issues#4]
Include the sections and subsections in the table of content.  The user should be able to navigate directly to a section and/or subsection.

```xml
<template>
  <div class="toc">
    <h1>{{ book.title }}</h1>
    <p>{{ book.description }}</p>
    <h2>Chapters</h2>
    <div v-for="chapter in book.chapters" :key="chapter.title">
      <h3>{{ chapter.title }}</h3>
      <p>{{ chapter.description }}</p>
      <div v-for="section in chapter.sections" :key="section.title">
        <h4>{{ section.title }}</h4>
        <p>{{ section.description }}</p>
        <div v-for="subsection in section.subsections" :key="subsection.title">
          <h5>{{ subsection.title }}</h5>
          <p>{{ subsection.description }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
```

## Tasks

- [ ] Update the model 
  The [backend model](https://github.com/sociable-weaver/app-java-boot/blob/9e69e2bebbf5818bc08c20dbe6fcf7580ee241da/src/main/java/aa/sw/open/OpenService.java#L16-L23) may need to be updated too.  In such case, we also need to update the link from where the application is downloaded to point to the new version.
- [ ] Render each menu level (similar to above)
- [ ] (Optional) Allow the user to search/filter the table of content
  If this is too complex, we will move it to its own story
- [ ] (Optional) Make the menu collapsable
  If this is too complex, we will move it to its own story
